---
driver:
  name: vagrant
  use_sudo: false

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.9.4

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - systemctl enable sshd.service

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
